package com.sunrise.orchestrator.type;

public enum ChatEventType {
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    MESSAGES_READ_UP_TO,
    CHAT_MEMBER_ADDED,
    CHAT_MEMBERS_ADDED,
    CHAT_MEMBER_INFO_UPDATE,
    CHAT_MEMBER_REMOVED,
    CHAT_MEMBER_ADMIN_UPDATED,
    CHAT_CREATED_WITH_MEMBERS,
    CHAT_UPDATED,
    CHAT_DELETED,
    CHAT_RESTORED
}
