package com.sunrise.orchestrator.event;

public enum EventType {

    // USER EVENTS
    USER_CHAT_CREATED,
    USER_CHAT_ADDED,
    USER_CHAT_REMOVED,
    USER_CHAT_DELETED,
    USER_CHAT_SETTINGS_CHANGED,
    USER_CHAT_MESSAGE_SENT,

    // CHAT EVENTS
    CHAT_CREATED,
    CHAT_UPDATED,
    CHAT_DELETED,
    
    // CHAT MEMBER EVENTS
    CHAT_MEMBER_ADDED,
    CHAT_MEMBERS_ADDED,
    CHAT_MEMBER_INFO_UPDATE,
    CHAT_MEMBER_REMOVED,
    CHAT_MEMBER_ADMIN_UPDATED,

    // MESSAGE EVENTS
    MESSAGE_CREATED_FULL,
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    MESSAGES_READ_UP_TO
}
